apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  receivers:
    slack:
      channel: "{{slack-channel}}"
      prependText: "{{slack-notify-type}}"
  alerts:
    - alert: Applikasjon nede
      severity: danger
      expr: kube_deployment_status_replicas_available{deployment="{{app}}"} == 0
      for: 2m
      description: "App \{{ $labels.deployment }} er nede i namespace \{{ $labels.namespace }}"
      action: "`kubectl describe pod \{{ $labels.deployment }} -n \{{ $labels.namespace }}` for events, og `kubectl logs -l \{{ $labels.deployment }} -n \{{ $labels.namespace }}` for logger"

    - alert: Høy error feilrate i logger
      severity: danger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="{{app}}",log_level=~"Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="{{app}}"}[3m]))) > 1
      for: 3m
      description: "Høy error feilrate på \{{ $labels.log_app }} i \{{ $labels.log_namespace }}"
      action: "Sjekk loggene til app \{{ $labels.log_app }} i namespace \{{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"

    - alert: Høy warning feilrate i logger
      severity: warning
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="{{app}}",log_level=~"Warning"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="{{app}}"}[3m]))) > 10
      for: 3m
      description: "Høy warning feilrate på \{{ $labels.log_app }} i \{{ $labels.log_namespace }}"
      action: "Sjekk loggene til app \{{ $labels.log_app }} i namespace \{{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"

    - alert: Høy andel HTTP serverfeil (5xx responser)
      severity: danger
      expr: (100 * (sum by (backend) (rate(response_total{status_code=~"^5\\d\\d", namespace="{{namespace}}", app="{{app}}"}[3m])) / sum by (backend) (rate(response_total{namespace="{{namespace}}", app="{{app}}"}[3m])))) > 1
      for: 3m
      description: "Høy andel HTTP serverfeil (5xx responser) på \{{ $labels.log_app }} i \{{ $labels.log_namespace }}"
      action: "Sjekk loggene til app \{{ $labels.log_app }} i namespace \{{ $labels.log_namespace }}, for å se hvorfor det returneres mye HTTP 5xx feilresponser"

    - alert: Høy andel HTTP klientfeil (4xx responser)
      severity: warning
      expr: (100 * (sum by (backend) (rate(response_total{status_code=~"^4\\d\\d", namespace="{{namespace}}", app="{{app}}"}[3m])) / sum by (backend) (rate(response_total{namespace="{{namespace}}", app="{{app}}"}[3m])))) > 10
      for: 3m
      description: "Høy andel HTTP klientfeil (4xx responser) på \{{ $labels.log_app }} i \{{ $labels.log_namespace }}"
      action: "Sjekk loggene til app \{{ $labels.log_app }} i namespace \{{ $labels.log_namespace }}, for å se hvorfor det for å se hvorfor det returneres mye HTTP 4xx feilresponser"