APP_NAME = "sokos-ktor-template"
NAMESPACE = "okonomi"

APPLICATION_PROFILE = "LOCAL"
USE_AUTHENTICATION="false"
DUMMY_PROPERTY = "Lucy"
SOME_OTHER_PROPERTY = "Lily"

#Postgres
POSTGRES_HOST=""
POSTGRES_PORT="123"
POSTGRES_NAME=""
POSTGRES_USERNAME=""
POSTGRES_PASSWORD=""
INIT_DB="false"