include file("defaults.conf")

application{
  nais{
    app_name = "local"
    namespace = "local"
  }
  development = true
}
properties{
  Katt1 = "Lucy"
  Katt2 = "Lily"
}
security{
  azure{
    enabled = false
    client_id = ${AZURE_APP_CLIENT_ID}
    well_known_url = ${AZURE_APP_WELL_KNOWN_URL}
  }
  vault {
    enabled = false
    url = ""
  }
}
database{
  host = "local-db"
  port = 1234
  name = "db-navn"
  vault_mountpath = "postgresql/preprod-fss/"
  username = ${POSTGRES_USERNAME}
  password = ${POSTGRES_PASSWORD}
}
