ktor {
  environment = test
}


dummy_properties{
  katt1 = "Lucy"
  katt2 = "Lily"
}
application {
  development = false
  nais {
    app_name = "test"
    namespace = "test"
  }
}

security {
  azure {
    enabled = false
    client_id = ""
    well_known_url = ""
  }
  vault {
    enabled = false
    url = ""
  }
}

database{
  host = ""
  port = 1234
  name = ""
  init_db = false
  vault_mountpath = ""
  username = ""
  password = ""
}

