include "application-dev-local.conf"

application{
  nais{
    app_name = "application"
    namespace = "okonomi"
  }
}

security {
  vault {
    enabled = true
    url = "https://vault.dev.nav.no"
  }
  azure{
    enabled = true
  }
}
database{
  host="dev-db"
  username = ""
  password = ""
}
