include file("defaults.properties")

application {
    appName = "sokos-ktor-template"
    appName = ${?NAIS_APP_NAME}
    namespace = "okonomi"
    namespace = ${?NAIS_NAMESPACE}
}

azureAd {
    clientId = ""
    clientId = ${?AZURE_APP_CLIENT_ID}
    wellKnownUrl = ""
    wellKnownUrl = ${?AZURE_APP_WELL_KNOWN_URL}
}
