# Denne inkluderer default.properties, som inneholder alle miljøer i dev
# Ønsker du å overstyre noen av verdiene i dev, kan du gjøre det her
include "application-dev.conf"

application {
    profile = LOCAL
    useAuthentication = false
}
