#!/bin/bash

# Function to center text
center_text() {
    termwidth=$(tput cols)
    padding=$(printf '%0.1s' " "{1..500})
    printf '%*.*s %s %*.*s\n' 0 "$(((termwidth - ${#1}) / 2))" "$padding" "$1" 0 "$(((termwidth - ${#1}) / 2))" "$padding"
}

echo ""
center_text "*********************************************************"
center_text "Running git pre-commit hook. Running Ktlint... "
center_text "*********************************************************"
echo ""

# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# Run ktlintCheck
./gradlew ktlintCheck

ktlintCheckStatus=$?

if [ "$ktlintCheckStatus" = 0 ] ; then
    echo ""
    center_text "*********************************************************"
    center_text "       ********************************************      "
    center_text "              Ktlint - no violations found"
    center_text "       ********************************************      "
    center_text "*********************************************************"
    echo ""

    # Add staged file changes to git
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add $file
      fi
    done
    #Exit
    exit 0
else
    echo ""
    center_text "*********************************************************"
    center_text "       ********************************************      "
    center_text "                  Ktlint - found violations"
    center_text "              Running ktlintFormat to fix issues..."
    center_text "       ********************************************      "
    center_text "*********************************************************"
    echo ""

    # Run ktlintFormat
    ./gradlew ktlintFormat

    # Run ktlintCheck again to verify if issues are fixed
    ./gradlew ktlintCheck

    ktlintCheckStatus=$?

    if [ "$ktlintCheckStatus" = 0 ] ; then
        echo ""
        center_text "*********************************************************"
        center_text "       ********************************************      "
        center_text "                    Ktlint - issues fixed"
        center_text "       ********************************************      "
        center_text "*********************************************************"
        echo ""

        # Add staged file changes to git
        for file in $stagedFiles; do
          if test -f "$file"; then
            git add $file
          fi
        done
        #Exit
        exit 0
    else
        echo ""
        center_text "*********************************************************"
        center_text "       ********************************************      "
        center_text "        Ktlint - found violations it could not fix."
        center_text "        Fix the issues before trying to commit again."
        center_text "       ********************************************      "
        center_text "*********************************************************"
        echo ""

        #Exit
        exit 1
    fi
fi