name: Build & test PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.editorconfig'
      - 'setupLocalEnvironment.sh'
      - '.scripts'
      - 'dokumentasjon/**'
      - '.github/workflows/codeql-trivy-scan.yaml'
      - '.github/workflows/deploy.yaml'
      - '.github/workflows/digestabot-automerge.yaml'
      - '.github/workflows/digestabot-update.yaml'
      - '.github/workflows/manual-deploy.yaml'
      - '.github/dependabot.yaml'
      - '.nais/**'

env:
  TZ: Europe/Oslo

jobs:
  build-and-test:
    permissions:
      contents: read
      actions: write
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build-test-app.yaml@main
    with:
      generate-dependency-graph: true

  dependency-review:
    needs: build-and-test
    permissions:
      contents: read
      pull-requests: write
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-dependency-review.yaml@feature/gradle_dependencies_review
    with:
      fail-on-severity: 'high'
      comment-summary-in-pr: 'always'
      warn-only: false

