name: Build/test PR

on:
  pull_request:

jobs:
  build-pr:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name and title
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          PR_TITLE=${{ github.event.pull_request.title }}
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|chore|refactor|docs)/ ]] || [[ ! "$PR_TITLE" =~ ^(feature|bugfix|hotfix|chore|refactor|docs)/ ]]; then
            echo "Branch name or PR title does not match the required prefixes."
            exit 1
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew --configuration-cache build shadowJar
