name: Deploy application

on:
  push:
    branches:
      - main
env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/moby-gha-workflows/.github/workflows/build-push-image.yaml@main
    secrets: inherit

  deploy-dev:
    needs: build
    name: Deploy to dev-gcp
    uses: navikt/moby-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}

#  deploy-prod:
#    needs: [build, deploy-dev]
#    name: Deploy to prod-gcp
#    uses: navikt/moby-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
#    with:
#      cluster: prod-gcp
#      resource: .nais/naiserator-prod.yaml
#      image: ${{ needs.build.outputs.image }}
