name: Deploy application

on:
  push:
    branches:
      - main
env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/moby-gha-workflows/.github/workflows/build-push-image.yaml@main
    secrets: inherit

  deploy:
    needs: build
    name: Deploy to dev
    uses: navikt/moby-gha-workflows/.github/workflows/nais-deploy.yaml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ job.build.outputs.image }}

