name: Deploy application

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.editorconfig'
      - 'setupLocalEnvironment.sh'
      - 'dokumentasjon/**'
      - '.github/workflows/build-pr.yaml'
      - '.github/workflows/manual-deploy-dev.yaml'
      - '.github/workflows/security.yaml'
      - '.github/workflows/alerts.yaml'
      - '.nais/alerts-dev.yaml'
      - '.nais/alerts-prod.yaml'
      - '.github/dependabot.yaml'
env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/moby-gha-workflows/.github/workflows/build-push-image.yaml@main
    secrets: inherit

  deploy:
    needs: build
    secrets: inherit
    name: Deploy to dev
    uses: navikt/moby-gha-workflows/.github/workflows/nais-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}