name: Deploy application

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.editorconfig'
      - 'setupLocalEnvironment.sh'
      - 'dokumentasjon/**'
      - '.github/workflows/build-pr.yaml'
      - '.github/workflows/manual-deploy.yaml'
      - '.github/workflows/security.yaml'
      - '.github/dependabot.yaml'

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build-app:
    name: Build & test application
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build.yaml@new_workflow_release
    secrets: inherit
    with:
      gradle-task: './gradlew build installDist --configuration-cache'

  build-image-dev:
    needs: build-app
    name: Build & push image for dev
    uses: navikt/mob-gha-workflows/.github/workflows/gar-image-push.yaml@new_workflow_release
    secrets: inherit
    with:
      dockerfile-path: './nais/Dockerfile'

  deploy-dev:
    needs: [ build-app, build-image-dev ]
    name: Deploy to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/naiserator.yaml
      image: ${{ needs.build.outputs.image }}


  build-image-prod:
    needs: [ build-app , deploy-dev ]
    name: Build & push image for prod
    uses: navikt/mob-gha-workflows/.github/workflows/gar-image-push.yaml@new_workflow_release
    secrets: inherit
    with:
      dockerfile-path: '.nais/Dockerfile'

  deploy-prod:
    needs: [build-app, build-image-prod]
    name: Deploy to prod-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: prod-fss
      resource: .nais/naiserator.yaml
      image: ${{ needs.build.outputs.image }}
