name: Deploy application manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build-app:
    name: Build & test application
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build.yaml@new_workflow_release
    secrets: inherit
    with:
      gradle-task: './gradlew build installDist --configuration-cache'

  build-image-dev:
    needs: build-app
    name: Build & push image for dev
    uses: navikt/mob-gha-workflows/.github/workflows/gar-image-push.yaml@new_workflow_release
    secrets: inherit
    with:
      image-tag: snapshot
      docker-context: '.nais/dev'
      dockerfile: './nais/dev/Dockerfile'
