name: Deploy application manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build-app:
    name: Build & test application
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build.yaml@new_workflow_release
    secrets: inherit
    with:
      gradle-task: './gradlew build installDist --configuration-cache'

  build-dev-image:
    needs: build-app
    name: Build & push image for dev
    uses: navikt/mob-gha-workflows/.github/workflows/gar-image-push.yaml@new_workflow_release
    secrets: inherit
    with:
      image-tag: snapshot
      dockerfile: './.nais/dev/Dockerfile'
      docker-context: './.nais/dev'

  deploy-dev:
    needs: [ build-app, build-dev-image ]
    name: Deploy to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/dev/naiserator.yaml
      image: ${{ needs.build-dev-image.outputs.image }}
